name: build

on:
  push:
      paths-ignore:
        - '**/*.md'
        - '.gitignore'
        - '.dependabot/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: build dependencies
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          version: latest

      - name: docker hub login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: build
        run: |
          cd 12-3.1
          docker buildx build \
            --push \
            --tag robertbeal/postgis:12 \
            --platform linux/arm64/v8 .

