name: build

on:
  push:
      paths-ignore:
        - '**/*.md'
        - '.gitignore'
        - '.dependabot/**'

jobs:
  build:
    strategy:
      matrix:
        version: ['10-2.5', 10-3.1', '12-2.5', '12-3.1']
        variant: [default, alpine]

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
      - uses: actions/checkout@v2

      - name: build dependencies
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          version: latest

      - name: docker hub login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: ${{ matrix.version }}-${{ matrix.variant }}
        run: |
          cd ${{ matrix.version }}-/${{ matrix.variant }}
          docker buildx build \
            --push \
            --tag robertbeal/postgis:${{ matrix.version }}-${{ matrix.variant }} \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8 .

